# Generated by Django 5.2.1 on 2025-05-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='affaire.affaire', verbose_name='Affaire associée')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_upload'],
            },
        ),
    ]
