# Generated by Django 5.2.1 on 2025-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('PARTICULIER', 'Particulier'), ('ENTREPRISE', 'Entreprise')], max_length=20),
        ),
    ]
