# Generated by Django 5.2.1 on 2025-05-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_emission', models.DateField()),
                ('statut_paiement', models.CharField(choices=[('PAYE', 'Payé'), ('EN_ATTENTE', 'En attente'), ('PAYEMENT_PARTIEL', 'Payement partiel')])),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affaire.affaire')),
            ],
        ),
    ]
