# Generated by Django 5.2.1 on 2025-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='statut_paiement',
            field=models.CharField(choices=[('PAYE', 'Payé'), ('EN_ATTENTE', 'En attente'), ('PAYEMENT_PARTIEL', 'Payement partiel')], max_length=20),
        ),
    ]
