# Generated by Django 5.2.1 on 2025-05-30 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaire', '0002_initial'),
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='affaire.affaire', verbose_name='Affaire associée'),
        ),
    ]
