# Generated by Django 5.2.1 on 2025-05-29 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name="Référence de l'affaire")),
                ('date_ouverture', models.DateField(blank=True, null=True, verbose_name="Date d'ouverture")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('PARTIELLEMENT_PAYE', 'Partiellement payé'), ('ANNULE', 'Annulé'), ('CLOTURE', 'Clôturé')], default='EN_ATTENTE', max_length=20, verbose_name="Statut de l'affaire")),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'affaire")),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('frais', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frais juridiques')),
            ],
            options={
                'verbose_name': 'Affaire',
                'verbose_name_plural': 'Affaires',
                'ordering': ['-date_ouverture'],
                'permissions': [('changer_statut', 'Peut modifier le statut des affaires'), ('voir_toutes_affaires', 'Peut voir toutes les affaires (même celles des autres avocats)')],
            },
        ),
    ]
