# Generated by Django 5.2.1 on 2025-05-29 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affaire', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='avocat_responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'AVOCAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires_en_charge', to=settings.AUTH_USER_MODEL, verbose_name='Avocat responsable'),
        ),
        migrations.AddField(
            model_name='affaire',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affaires', to='clients.client', verbose_name='Client associé'),
        ),
    ]
