# Generated by Django 5.2.1 on 2025-05-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaire', '0001_initial'),
        ('clients', '0002_alter_client_type_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client associé'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='date_ouverture',
            field=models.DateField(verbose_name="Date d'ouverture"),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name="Référence de l'affaire"),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], max_length=20, verbose_name="Statut de l'affaire"),
        ),
    ]
